### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Tilian-HURE** [Tilian-HURE/Tangularot#1]
# À faire

## Parties dans la BD JSON et observateurs
- [ ] Création d'un service pour les parties connecté à la BD JSON
- [ ] Création d'un environnement pour les parties afin de rendre les éléments de la BD observables

## Ajout de nouvelles parties
- [ ] Ajout de nouvelles parties dans la BD JSON (utilisation du service pour les parties)

## Affichage des parties dans l'accueil
- [ ] Affichage des parties récupérées avec un observateur

## Header
- [ ] Affichage des parties dans la liste déroulante
- [ ] Création et complétion d'une page "À propos" (composant et route)
